version: "3.8"
services:
  app:
    build: .
    environment:
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - .:/code